'use strict';
const KEY='nitroVelocityStateV1';
const defaults={playerId:'',loggedIn:false,remember:true,cash:125000,xp:12,car:'audi',color:'#111820',rim:0,steering:'tilt',graphics:'ultra',motion:true,music:80,sfx:90,muted:false,assist:true,police:true,track:'city',bestTime:null};
const cars={audi:{name:'Audi R8 V10',tag:'SPORTS CAR',cls:'car-audi',stats:{'Top Speed':90,'Acceleration':84,'Handling':87,'Braking':89,'Nitro':91}},range:{name:'Range Rover',tag:'SUV',cls:'car-range',stats:{'Top Speed':72,'Acceleration':68,'Handling':76,'Braking':82,'Nitro':80}},thar:{name:'Thar',tag:'OFF-ROAD',cls:'car-thar',stats:{'Top Speed':66,'Acceleration':70,'Handling':84,'Braking':78,'Nitro':86}}};
const colors=[['#111820','Obsidian'],['#eef3f6','Pearl'],['#e6382c','Red'],['#0878ff','Electric Blue'],['#ff9d16','Sunset Orange'],['#21a86b','Emerald']];
let state=loadState(), raceTimer=null, raceStart=0, speed=198, nitro=76, busted=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return {...defaults}}}
function save(){try{const toStore=state.remember?state:{...state,loggedIn:false};localStorage.setItem(KEY,JSON.stringify(toStore))}catch(e){} updateWallet()}
function updateWallet(){if($('#cashValue'))$('#cashValue').textContent='$'+state.cash.toLocaleString();if($('#xpValue'))$('#xpValue').textContent='XP '+state.xp}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function requireLogin(screen){if(!state.loggedIn){showScreen('login');$('#loginMessage').textContent='Please create your driver profile first.';$('#loginMessage').className='message bad';return false}return true}
function showScreen(id){if(id!=='login'&&!requireLogin(id))return;$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.topnav .nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));if(id==='race')startRace();else stopRace();window.scrollTo({top:0,behavior:'smooth'})}
function bindNavigation(){ $$('[data-screen]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen))); }
function renderGarage(){const car=cars[state.car];$('#carVisual').className='car-visual '+car.cls;$('#carVisual').style.filter=`drop-shadow(0 0 18px ${state.color}55)`;$('#carVisual').style.background=`linear-gradient(90deg,${shade(state.color,-25)},${state.color},${shade(state.color,-35)})`;$('#carName').textContent=car.name;$('#carTag').textContent=car.tag;$('#stats').innerHTML=Object.entries(car.stats).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${k==='Top Speed'?(v===90?'268':v===72?'228':'198'):(v/10).toFixed(1)}</b><div class="trackbar"><i style="width:${v}%"></i></div></div>`).join('');$('#colors').innerHTML=colors.map(([c,n])=>`<button class="swatch ${c.toLowerCase()===state.color.toLowerCase()?'selected':''}" style="background:${c}" title="${n}" aria-label="${n} paint" data-color="${c}"></button>`).join('');$('#rims').innerHTML=[0,1,2,3].map(i=>`<button class="rim ${i===state.rim?'selected':''}" data-rim="${i}" aria-label="Rim ${i+1}"></button>`).join('');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.car===state.car));$$('[data-color]').forEach(b=>b.addEventListener('click',()=>{state.color=b.dataset.color;save();renderGarage();toast('Paint updated')}));$$('[data-rim]').forEach(b=>b.addEventListener('click',()=>{state.rim=Number(b.dataset.rim);save();renderGarage();toast('Rim updated')}));}
function shade(hex,amt){let h=hex.replace('#','');if(h.length!==6)return hex;let n=parseInt(h,16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,((n>>8)&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return '#'+[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bindGarage(){$$('.tab').forEach(t=>t.addEventListener('click',()=>{state.car=t.dataset.car;save();renderGarage();toast(cars[state.car].name+' selected')}));renderGarage()}
function bindSettings(){$$('.setting-nav').forEach(b=>b.addEventListener('click',()=>{$$('.setting-nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.setting-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===b.dataset.settingTab))}));$$('[data-steering]').forEach(b=>b.addEventListener('click',()=>{state.steering=b.dataset.steering;save();renderSettings();toast('Steering mode saved')}));$$('[data-graphics]').forEach(b=>b.addEventListener('click',()=>{state.graphics=b.dataset.graphics;save();renderSettings();toast('Graphics set to '+b.dataset.graphics.toUpperCase())}));$('#motionToggle').addEventListener('change',e=>{state.motion=e.target.checked;save()});$('#musicRange').addEventListener('input',e=>{state.music=+e.target.value;$('#musicOut').textContent=state.music+'%';save()});$('#sfxRange').addEventListener('input',e=>{state.sfx=+e.target.value;$('#sfxOut').textContent=state.sfx+'%';save()});$('#muteToggle').addEventListener('click',()=>{state.muted=!state.muted;save();renderSettings();toast(state.muted?'Audio muted':'Audio unmuted')});$('#assistToggle').addEventListener('change',e=>{state.assist=e.target.checked;save()});$('#policeToggle').addEventListener('change',e=>{state.police=e.target.checked;save();toast(state.police?'Police pursuit enabled':'Police pursuit disabled')});$('#resetSettings').addEventListener('click',()=>{Object.assign(state,{steering:defaults.steering,graphics:defaults.graphics,motion:defaults.motion,music:defaults.music,sfx:defaults.sfx,muted:defaults.muted,assist:defaults.assist,police:defaults.police});save();renderSettings();toast('Settings reset')});renderSettings()}
function renderSettings(){$$('[data-steering]').forEach(b=>b.classList.toggle('selected',b.dataset.steering===state.steering));$$('[data-graphics]').forEach(b=>b.classList.toggle('selected',b.dataset.graphics===state.graphics));$('#steeringStatus').textContent='Current: '+({tilt:'Tilt to Steer',touch:'Touch Left / Right',wheel:'Virtual Steering Wheel'}[state.steering]);$('#graphicsStatus').textContent='Quality: '+state.graphics.toUpperCase();$('#motionToggle').checked=state.motion;$('#musicRange').value=state.music;$('#sfxRange').value=state.sfx;$('#musicOut').textContent=state.music+'%';$('#sfxOut').textContent=state.sfx+'%';$('#muteToggle').textContent=state.muted?'Unmute All':'Mute All';$('#assistToggle').checked=state.assist;$('#policeToggle').checked=state.police}
function bindTracks(){$$('.track-card').forEach(b=>b.addEventListener('click',()=>{state.track=b.dataset.track;save();renderTracks();toast('Track selected')}));renderTracks()}
function renderTracks(){const names={city:'Neon City Highway',desert:'Sunny Desert Canyon',mountain:'Mountain Pass'};$$('.track-card').forEach(b=>b.classList.toggle('selected',b.dataset.track===state.track));$('#trackStatus').textContent=names[state.track]+' selected'}
function bindMissions(){$$('.mission').forEach(b=>b.addEventListener('click',()=>{const names={street:'Street Race mission accepted',escort:'Escort mission accepted',takedown:'Take Down mission accepted'};$('#missionStatus').textContent=names[b.dataset.mission]+' — heading to route.';$('#missionStatus').className='message good';toast('Mission accepted')}))}
function applyRaceContext(){const wrap=$('#raceWrap');if(wrap){wrap.classList.remove('track-city','track-desert','track-mountain');wrap.classList.add('track-'+state.track)}const car=$('.race-car');if(car)car.style.background=`linear-gradient(90deg,${shade(state.color,-25)},${state.color},${shade(state.color,-35)})`}
function startRace(){if(raceTimer)return;applyRaceContext();speed=198;nitro=76;raceStart=performance.now();$('#speedValue').textContent=speed;$('#nitroFill').style.width=nitro+'%';$('#policeAlert').style.display=state.police?'block':'none';raceTimer=setInterval(()=>{const t=(performance.now()-raceStart)/1000;const wave=Math.sin(t*2.1)*16;speed=Math.max(142,Math.min(286,Math.round(198+wave+(nitro<25?-12:0))));$('#speedValue').textContent=speed;$('#rpmValue').textContent=(5.5+speed/120).toFixed(1);$('#gearValue').textContent=Math.max(3,Math.min(7,Math.floor(speed/42)));$('#raceTime').textContent=formatTime(t);nitro=Math.max(0,nitro-(state.muted?0.025:0.04));$('#nitroFill').style.width=nitro+'%';},100)}
function stopRace(){if(raceTimer){clearInterval(raceTimer);raceTimer=null}}
function formatTime(t){const m=Math.floor(t/60),s=(t%60).toFixed(1).padStart(4,'0');return String(m).padStart(2,'0')+':'+s}
function boost(){if(!raceTimer){showScreen('race');return}if(nitro<=2){toast('Nitro depleted');return}nitro=Math.min(100,nitro+22);speed=Math.min(320,speed+55);$('#speedValue').textContent=speed;$('#nitroFill').style.width=nitro+'%';toast('NITRO BOOST!')}
function triggerBusted(){if(!raceTimer)return;const elapsed=(performance.now()-raceStart)/1000;state.bestTime=state.bestTime?Math.min(state.bestTime,elapsed):elapsed;save();stopRace();$('#bestTime').textContent=formatTime(state.bestTime);$('#bustedCash').textContent=state.cash.toLocaleString();showScreen('busted')}
function bindRace(){$('#nitroBtn').addEventListener('click',boost);$('#bustedBtn').addEventListener('click',triggerBusted);$('#retryBtn').addEventListener('click',()=>showScreen('race'));$('#returnHubBtn').addEventListener('click',()=>showScreen('hub'))}
function bindLogin(){$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#playerId').value.trim(),pw=$('#password').value;if(id.length<3){setLogin('Player ID must be at least 3 characters.','bad');return}if(pw.length<4){setLogin('Password must be at least 4 characters.','bad');return}state.loggedIn=true;state.playerId=id;state.remember=$('#rememberMe').checked;save();setLogin('Profile ready. Loading open world…','good');setTimeout(()=>showScreen('hub'),120)});if(state.loggedIn&&state.playerId)$('#playerId').value=state.playerId;$('#rememberMe').checked=state.remember!==false}
function setLogin(msg,type){$('#loginMessage').textContent=msg;$('#loginMessage').className='message '+type}
function init(){updateWallet();bindNavigation();bindLogin();bindGarage();bindSettings();bindTracks();bindMissions();bindRace();if(state.loggedIn)showScreen('hub');else showScreen('login')}
document.addEventListener('DOMContentLoaded',init);
